// Mocks generated by Mockito 5.4.5 from annotations
// in workoutride/test/usecase/get_calculated_power_meter_data_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workoutride/domain/model/power_meter_data.dart' as _i2;
import 'package:workoutride/domain/usecase/get_power_meter_data_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePowerMeterData_0 extends _i1.SmartFake
    implements _i2.PowerMeterData {
  _FakePowerMeterData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPowerMeterDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPowerMeterDataUseCase extends _i1.Mock
    implements _i3.GetPowerMeterDataUseCase {
  MockGetPowerMeterDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get lastCrankRevolutions => (super.noSuchMethod(
        Invocation.getter(#lastCrankRevolutions),
        returnValue: 0,
      ) as int);

  @override
  set lastCrankRevolutions(int? _lastCrankRevolutions) => super.noSuchMethod(
        Invocation.setter(
          #lastCrankRevolutions,
          _lastCrankRevolutions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get lastCrankEventTime => (super.noSuchMethod(
        Invocation.getter(#lastCrankEventTime),
        returnValue: 0,
      ) as int);

  @override
  set lastCrankEventTime(int? _lastCrankEventTime) => super.noSuchMethod(
        Invocation.setter(
          #lastCrankEventTime,
          _lastCrankEventTime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Stream<_i2.PowerMeterData> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Stream<_i2.PowerMeterData>.empty(),
      ) as _i4.Stream<_i2.PowerMeterData>);

  @override
  _i2.PowerMeterData processData(List<int>? value) => (super.noSuchMethod(
        Invocation.method(
          #processData,
          [value],
        ),
        returnValue: _FakePowerMeterData_0(
          this,
          Invocation.method(
            #processData,
            [value],
          ),
        ),
      ) as _i2.PowerMeterData);
}
