// Mocks generated by Mockito 5.4.5 from annotations
// in workoutride/test/data/repository/workout_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workoutride/data/remote/api/workout_api_client.dart' as _i4;
import 'package:workoutride/data/remote/model/workout_block_dto.dart' as _i6;
import 'package:workoutride/data/remote/model/workout_result_dto.dart' as _i3;
import 'package:workoutride/data/remote/model/workout_summary_dto.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkoutSummaryDto_0 extends _i1.SmartFake
    implements _i2.WorkoutSummaryDto {
  _FakeWorkoutSummaryDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkoutResultDto_1 extends _i1.SmartFake
    implements _i3.WorkoutResultDto {
  _FakeWorkoutResultDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkoutApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutApiClient extends _i1.Mock implements _i4.WorkoutApiClient {
  MockWorkoutApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.WorkoutSummaryDto>> getWorkoutSummaries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutSummaries,
          [],
        ),
        returnValue: _i5.Future<List<_i2.WorkoutSummaryDto>>.value(
            <_i2.WorkoutSummaryDto>[]),
      ) as _i5.Future<List<_i2.WorkoutSummaryDto>>);

  @override
  _i5.Future<_i2.WorkoutSummaryDto> getWorkoutSummary(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutSummary,
          [id],
        ),
        returnValue:
            _i5.Future<_i2.WorkoutSummaryDto>.value(_FakeWorkoutSummaryDto_0(
          this,
          Invocation.method(
            #getWorkoutSummary,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.WorkoutSummaryDto>);

  @override
  _i5.Future<List<_i6.WorkoutBlockDto>> getWorkoutBlocks(int? workoutId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutBlocks,
          [workoutId],
        ),
        returnValue: _i5.Future<List<_i6.WorkoutBlockDto>>.value(
            <_i6.WorkoutBlockDto>[]),
      ) as _i5.Future<List<_i6.WorkoutBlockDto>>);

  @override
  _i5.Future<List<_i3.WorkoutResultDto>> getWorkoutResults() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutResults,
          [],
        ),
        returnValue: _i5.Future<List<_i3.WorkoutResultDto>>.value(
            <_i3.WorkoutResultDto>[]),
      ) as _i5.Future<List<_i3.WorkoutResultDto>>);

  @override
  _i5.Future<_i3.WorkoutResultDto> getWorkoutResult(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutResult,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.WorkoutResultDto>.value(_FakeWorkoutResultDto_1(
          this,
          Invocation.method(
            #getWorkoutResult,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.WorkoutResultDto>);

  @override
  _i5.Future<_i3.WorkoutResultDto> saveWorkoutResult(
          Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWorkoutResult,
          [body],
        ),
        returnValue:
            _i5.Future<_i3.WorkoutResultDto>.value(_FakeWorkoutResultDto_1(
          this,
          Invocation.method(
            #saveWorkoutResult,
            [body],
          ),
        )),
      ) as _i5.Future<_i3.WorkoutResultDto>);
}
