service: backend
image: workoutride-app/workoutride-staging/backend

servers:
  web:
    - 34.138.232.78

proxy:
  ssl: true
  host: 34.138.232.78.nip.io
  healthcheck:
    path: /up
    interval: 5
    timeout: 120

registry:
  server: us-east1-docker.pkg.dev
  username: oauth2accesstoken
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
  clear:
    SOLID_QUEUE_IN_PUMA: true
    GOOGLE_CLIENT_ID: "432477473655-2ovs5abgvf6cu6ke9gli7b5phgi0je4u.apps.googleusercontent.com"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "backend_storage:/rails/storage"

builder:
  arch: amd64

ssh:
  user: ohnaoki
  keys:
    - ~/.ssh/workoutride_deploy
