// Mocks generated by Mockito 5.4.5 from annotations
// in workoutride/test/ui/workout_detail/workout_detail_screen_state_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workoutride/domain/model/user_profile.dart' as _i10;
import 'package:workoutride/domain/model/workout/workout_block.dart' as _i7;
import 'package:workoutride/domain/model/workout/workout_result.dart' as _i3;
import 'package:workoutride/domain/model/workout/workout_result_draft.dart'
    as _i8;
import 'package:workoutride/domain/model/workout/workout_summary.dart' as _i2;
import 'package:workoutride/domain/repository/user_profile_repository.dart'
    as _i4;
import 'package:workoutride/domain/repository/workout_repository.dart' as _i5;
import 'package:workoutride/domain/usecase/user_profile/get_user_ftp_use_case.dart'
    as _i11;
import 'package:workoutride/domain/usecase/user_profile/get_user_profile_use_case.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkoutSummary_0 extends _i1.SmartFake
    implements _i2.WorkoutSummary {
  _FakeWorkoutSummary_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkoutResult_1 extends _i1.SmartFake implements _i3.WorkoutResult {
  _FakeWorkoutResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfileRepository_2 extends _i1.SmartFake
    implements _i4.UserProfileRepository {
  _FakeUserProfileRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutRepository extends _i1.Mock implements _i5.WorkoutRepository {
  MockWorkoutRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.WorkoutSummary>> getWorkoutSummaries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutSummaries,
          [],
        ),
        returnValue:
            _i6.Future<List<_i2.WorkoutSummary>>.value(<_i2.WorkoutSummary>[]),
      ) as _i6.Future<List<_i2.WorkoutSummary>>);

  @override
  _i6.Future<_i2.WorkoutSummary> getWorkoutSummary(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutSummary,
          [id],
        ),
        returnValue: _i6.Future<_i2.WorkoutSummary>.value(_FakeWorkoutSummary_0(
          this,
          Invocation.method(
            #getWorkoutSummary,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.WorkoutSummary>);

  @override
  _i6.Future<List<_i7.WorkoutBlock>> getWorkoutBlocks(int? workoutSummaryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutBlocks,
          [workoutSummaryId],
        ),
        returnValue:
            _i6.Future<List<_i7.WorkoutBlock>>.value(<_i7.WorkoutBlock>[]),
      ) as _i6.Future<List<_i7.WorkoutBlock>>);

  @override
  _i6.Future<List<_i3.WorkoutResult>> getWorkoutResults() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutResults,
          [],
        ),
        returnValue:
            _i6.Future<List<_i3.WorkoutResult>>.value(<_i3.WorkoutResult>[]),
      ) as _i6.Future<List<_i3.WorkoutResult>>);

  @override
  _i6.Future<_i3.WorkoutResult> getWorkoutResult(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutResult,
          [id],
        ),
        returnValue: _i6.Future<_i3.WorkoutResult>.value(_FakeWorkoutResult_1(
          this,
          Invocation.method(
            #getWorkoutResult,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.WorkoutResult>);

  @override
  _i6.Future<_i3.WorkoutResult> saveWorkoutResult(
          _i8.WorkoutResultDraft? draft) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWorkoutResult,
          [draft],
        ),
        returnValue: _i6.Future<_i3.WorkoutResult>.value(_FakeWorkoutResult_1(
          this,
          Invocation.method(
            #saveWorkoutResult,
            [draft],
          ),
        )),
      ) as _i6.Future<_i3.WorkoutResult>);
}

/// A class which mocks [GetUserProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserProfileUseCase extends _i1.Mock
    implements _i9.GetUserProfileUseCase {
  MockGetUserProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.UserProfileRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserProfileRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.UserProfileRepository);

  @override
  _i6.Future<_i10.UserProfile?> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<_i10.UserProfile?>.value(),
      ) as _i6.Future<_i10.UserProfile?>);
}

/// A class which mocks [GetUserFtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserFtpUseCase extends _i1.Mock implements _i11.GetUserFtpUseCase {
  MockGetUserFtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<int?> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<int?>.value(),
      ) as _i6.Future<int?>);
}
