// Mocks generated by Mockito 5.4.5 from annotations
// in workoutride/test/ui/workout_detail/workout_detail_screen_state_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workoutride/domain/model/user_profile.dart' as _i9;
import 'package:workoutride/domain/model/workout/workout_block.dart' as _i6;
import 'package:workoutride/domain/model/workout/workout_summary.dart' as _i2;
import 'package:workoutride/domain/repository/user_profile_repository.dart'
    as _i3;
import 'package:workoutride/domain/usecase/user_profile/get_user_profile_use_case.dart'
    as _i8;
import 'package:workoutride/domain/usecase/workout/get_workout_blocks_use_case.dart'
    as _i4;
import 'package:workoutride/domain/usecase/workout/get_workout_summary_use_case.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkoutSummary_0 extends _i1.SmartFake
    implements _i2.WorkoutSummary {
  _FakeWorkoutSummary_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfileRepository_1 extends _i1.SmartFake
    implements _i3.UserProfileRepository {
  _FakeUserProfileRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetWorkoutBlocksUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWorkoutBlocksUseCase extends _i1.Mock
    implements _i4.GetWorkoutBlocksUseCase {
  MockGetWorkoutBlocksUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.WorkoutBlock>> call(int? workoutId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [workoutId],
        ),
        returnValue:
            _i5.Future<List<_i6.WorkoutBlock>>.value(<_i6.WorkoutBlock>[]),
      ) as _i5.Future<List<_i6.WorkoutBlock>>);
}

/// A class which mocks [GetWorkoutSummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWorkoutSummaryUseCase extends _i1.Mock
    implements _i7.GetWorkoutSummaryUseCase {
  MockGetWorkoutSummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.WorkoutSummary> call(int? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i5.Future<_i2.WorkoutSummary>.value(_FakeWorkoutSummary_0(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.WorkoutSummary>);
}

/// A class which mocks [GetUserProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserProfileUseCase extends _i1.Mock
    implements _i8.GetUserProfileUseCase {
  MockGetUserProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UserProfileRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserProfileRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.UserProfileRepository);

  @override
  _i5.Future<_i9.UserProfile?> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i9.UserProfile?>.value(),
      ) as _i5.Future<_i9.UserProfile?>);
}
