// Mocks generated by Mockito 5.4.5 from annotations
// in workoutride/test/ui/workout/workout_screen_state_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workoutride/domain/model/power_meter_data.dart' as _i6;
import 'package:workoutride/domain/model/workout/workout_block.dart' as _i4;
import 'package:workoutride/domain/usecase/get_calculated_power_meter_data_usecase.dart'
    as _i5;
import 'package:workoutride/domain/usecase/workout/get_workout_blocks_use_case.dart'
    as _i2;
import 'package:workoutride/domain/usecase/workout/manage_workout_use_case.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetWorkoutBlocksUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWorkoutBlocksUseCase extends _i1.Mock
    implements _i2.GetWorkoutBlocksUseCase {
  MockGetWorkoutBlocksUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.WorkoutBlock>> call(int? workoutId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [workoutId],
        ),
        returnValue:
            _i3.Future<List<_i4.WorkoutBlock>>.value(<_i4.WorkoutBlock>[]),
      ) as _i3.Future<List<_i4.WorkoutBlock>>);
}

/// A class which mocks [GetCalculatedPowerMeterDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCalculatedPowerMeterDataUseCase extends _i1.Mock
    implements _i5.GetCalculatedPowerMeterDataUseCase {
  MockGetCalculatedPowerMeterDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i6.PowerMeterData> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Stream<_i6.PowerMeterData>.empty(),
      ) as _i3.Stream<_i6.PowerMeterData>);
}

/// A class which mocks [ManageWorkoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockManageWorkoutUseCase extends _i1.Mock
    implements _i7.ManageWorkoutUseCase {
  MockManageWorkoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isPaused => (super.noSuchMethod(
        Invocation.getter(#isPaused),
        returnValue: false,
      ) as bool);

  @override
  _i3.Stream<_i7.WorkoutFrame> call(List<_i4.WorkoutBlock>? blocks) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [blocks],
        ),
        returnValue: _i3.Stream<_i7.WorkoutFrame>.empty(),
      ) as _i3.Stream<_i7.WorkoutFrame>);

  @override
  void pauseWorkout() => super.noSuchMethod(
        Invocation.method(
          #pauseWorkout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumeWorkout() => super.noSuchMethod(
        Invocation.method(
          #resumeWorkout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
